apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongo-pvc.yaml
  - mongo-deployment.yaml
  - mongo-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - qdrant-deployment.yaml
  - qdrant-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
