apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: qdrant
  name: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qdrant
  template:
    metadata:
      labels:
        io.kompose.service: qdrant
    spec:
      containers:
        - image: qdrant/qdrant:latest
          name: qdrant
          ports:
            - containerPort: 6333
              protocol: TCP
            - containerPort: 6334
              protocol: TCP
      restartPolicy: Always
