apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: qdrant
  name: qdrant
spec:
  ports:
    - name: "6333"
      port: 6333
      targetPort: 6333
    - name: "6334"
      port: 6334
      targetPort: 6334
  selector:
    io.kompose.service: qdrant
