apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ushadow-tls
  namespace: ushadow
spec:
  dnsNames:
  - ushadow.chakra
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: local-ca-issuer
  secretName: ushadow-tls
  usages:
  - digital signature
  - key encipherment
