instances:
  openai-1:
    template_id: openai
    name: openai-1
    deployment_target: cloud
    status: n/a
    created_at: '2026-01-15T20:36:55.092787+00:00'
  openmemory-compose-mem0-unode-1768509418855:
    template_id: openmemory-compose:mem0
    name: OpenMemory (ushadow-purple)
    description: uNode deployment to ushadow-purple
    deployment_target: ushadow-purple
    status: stopped
    created_at: '2026-01-15T20:36:58.858635+00:00'
    deployment_id: 91f60bb2
    container_id: cf9ec7d53922a9d40babf69d5845c109b30d1931d74ca8bb1ebcf761232f6221
    container_name: mem0-91f60bb2
  openmemory-compose-mem0-unode-1768511009309:
    template_id: openmemory-compose:mem0
    name: OpenMemory (ushadow-purple)
    description: uNode deployment to ushadow-purple
    deployment_target: ushadow-purple
    status: error
    created_at: '2026-01-15T21:03:29.314118+00:00'
    error: 'Docker deployment failed: 500 Server Error for http+docker://localhost/v1.51/containers/c9ff4abaf1c15a28c7e6972004e1036b0f0a7f0559a4c8c81b4e6411b8941e10/start:
      Internal Server Error ("failed to set up container networking: driver failed
      programming external connectivity on endpoint mem0-1dce9e9c (66e4f0d502125429290ec142e2f2ac486d432ccf6d6ffa52ce8c671e1fdc2716):
      Bind for 0.0.0.0:8765 failed: port is already allocated")'
  openmemory-compose-mem0-unode-1768555072128:
    template_id: openmemory-compose:mem0
    name: OpenMemory (ushadow-purple)
    description: uNode deployment to ushadow-purple
    deployment_target: ushadow-purple
    status: stopped
    outputs:
      access_url: https://purple.spangled-kettle.ts.net/openmemory-compose:mem0
    created_at: '2026-01-16T09:17:52.180807+00:00'
    deployment_id: 4716fbe0
    container_id: 1ccf6ebcf9fe3b7c45d3c702262742090239a1fa99a90945d86ecfc27cc2c281
    container_name: mem0-4716fbe0
  openmemory-compose-mem0-unode-1768555097629:
    template_id: openmemory-compose:mem0
    name: OpenMemory (ushadow-purple)
    description: uNode deployment to ushadow-purple
    deployment_target: ushadow-purple
    status: stopped
    outputs:
      access_url: https://purple.spangled-kettle.ts.net/openmemory-compose:mem0
    created_at: '2026-01-16T09:18:17.648798+00:00'
    deployment_id: 13e2b5e8
    container_id: 749fdc055e33127a8befb7ee26b941a433e35a937ede432acecc1bd94cf97a25
    container_name: mem0-13e2b5e8
