instances:
  openai-1:
    template_id: openai
    name: oss
    config:
      model: gpt-oss
    deployment_target: cloud
    status: n/a
    created_at: '2026-01-04T14:18:43.443875+00:00'
  openai-2:
    template_id: openai
    name: openai-2
    config:
      model: xdsdf
      api_key: '123'
    deployment_target: cloud
    status: n/a
    created_at: '2026-01-04T14:19:23.753674+00:00'
  openai-3:
    template_id: openai
    name: red
    config: {}
    deployment_target: cloud
    status: n/a
    created_at: '2026-01-08T16:10:24.972709+00:00'
