defaults: {}
wiring:
- id: 9dc8a4aa
  source_instance_id: deepgram
  source_capability: transcription
  target_instance_id: chronicle-compose:chronicle-backend
  target_capability: transcription
- id: 3cacc293
  source_instance_id: openai-2
  source_capability: llm
  target_instance_id: openmemory-compose:mem0
  target_capability: llm
- id: 62a97a18
  source_instance_id: openai-3
  source_capability: llm
  target_instance_id: chronicle-compose:chronicle-backend
  target_capability: llm
