instances:
  openai-1:
    template_id: openai
    name: openai-1
    deployment_target: cloud
    status: n/a
    created_at: '2026-01-15T20:19:23.282751+00:00'
  openmemory-compose-mem0-unode-1768508366189:
    template_id: openmemory-compose:mem0
    name: OpenMemory (ushadow-purple)
    description: uNode deployment to ushadow-purple
    deployment_target: ushadow-purple
    status: running
    outputs:
      access_url: http://localhost:8765
    created_at: '2026-01-15T20:19:26.194496+00:00'
  openmemory-compose-mem0-unode-1768508494524:
    template_id: openmemory-compose:mem0
    name: OpenMemory (ushadow-purple)
    description: uNode deployment to ushadow-purple
    deployment_target: ushadow-purple
    status: running
    outputs:
      access_url: http://localhost:8765
    created_at: '2026-01-15T20:21:34.538624+00:00'
  openai-2:
    template_id: openai
    name: openai-2
    deployment_target: cloud
    status: n/a
    created_at: '2026-01-15T20:28:40.099964+00:00'
  openmemory-compose-mem0-unode-1768508923327:
    template_id: openmemory-compose:mem0
    name: OpenMemory (ushadow-purple)
    description: uNode deployment to ushadow-purple
    deployment_target: ushadow-purple
    status: running
    created_at: '2026-01-15T20:28:43.330992+00:00'
    deployment_id: 63a2c6f9
    container_id: c3da4a4475991d4d31bd096fd223b9df8296a78a707ec51024cb9e11be76a5ca
    container_name: mem0-63a2c6f9
  openmemory-compose-mem0-unode-1768508947058:
    template_id: openmemory-compose:mem0
    name: OpenMemory (ushadow-purple)
    description: uNode deployment to ushadow-purple
    deployment_target: ushadow-purple
    status: error
    created_at: '2026-01-15T20:29:07.068665+00:00'
    error: Service openmemory-compose:mem0 already deployed to ushadow-purple
