backend_port: 8000
deployment_mode:
  environment: dev
  mode: single
environments:
- dev
- test
- prod
frontend_port: 3000
hostname: gold.spangled-kettle.ts.net
https_enabled: true
use_caddy_proxy: false
