defaults: {}
wiring:
- id: 31e04a7c
  source_instance_id: openai-1
  source_capability: llm
  target_instance_id: chronicle-compose:chronicle-backend
  target_capability: llm
- id: '56324379'
  source_instance_id: deepgram-1
  source_capability: transcription
  target_instance_id: chronicle-compose:chronicle-backend
  target_capability: transcription
- id: 8ea7cb2c
  source_instance_id: openai-1
  source_capability: llm
  target_instance_id: openmemory-compose:mem0
  target_capability: llm
