defaults: {}
wiring:
- id: '56324379'
  source_config_id: deepgram-1
  source_capability: transcription
  target_config_id: chronicle-compose:chronicle-backend
  target_capability: transcription
- id: 8ea7cb2c
  source_config_id: openai-1
  source_capability: llm
  target_config_id: openmemory-compose:mem0
  target_capability: llm
- id: c090af2b
  source_config_id: openai-1
  source_capability: llm
  target_config_id: chronicle-compose:chronicle-backend
  target_capability: llm
