apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: BACKEND_PORT
              value: "8000"
            - name: CORS_ORIGINS
              value: http://localhost:3000
            - name: HOST
              value: 0.0.0.0
            - name: MONGODB_DATABASE
              value: ushadow
            - name: PORT
              value: "8000"
            - name: REDIS_URL
              value: redis://redis:6379/0
          image: backend
          name: ushadow-backend
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: compose-files
              mountPath: /compose
              readOnly: true
            - name: config-files
              mountPath: /config
              readOnly: true
      volumes:
        - name: compose-files
          configMap:
            name: compose-files
        - name: config-files
          configMap:
            name: config-files
      restartPolicy: Always
