apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: webui
  name: webui
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
  selector:
    io.kompose.service: webui
